# Generated by Django 3.1b1 on 2020-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('seriel_number', models.IntegerField(primary_key=10, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField(max_length=14)),
                ('state', models.IntegerField(max_length=20)),
                ('city', models.IntegerField(max_length=20)),
                ('desc', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
